"""empty message

Revision ID: 28d9a4eaf976
Revises: db80a2510d33
Create Date: 2019-05-28 09:05:48.781019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28d9a4eaf976'
down_revision = 'db80a2510d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('weeks', sa.Integer(), nullable=True),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_client_id'), 'issue', ['client_id'], unique=False)
    op.create_index(op.f('ix_issue_film_id'), 'issue', ['film_id'], unique=False)
    op.drop_index('ix_issuance_client_id', table_name='issuance')
    op.drop_index('ix_issuance_film_id', table_name='issuance')
    op.drop_table('issuance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('weeks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sum', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='issuance_client_id_fkey'),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name='issuance_film_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='issuance_pkey')
    )
    op.create_index('ix_issuance_film_id', 'issuance', ['film_id'], unique=False)
    op.create_index('ix_issuance_client_id', 'issuance', ['client_id'], unique=False)
    op.drop_index(op.f('ix_issue_film_id'), table_name='issue')
    op.drop_index(op.f('ix_issue_client_id'), table_name='issue')
    op.drop_table('issue')
    # ### end Alembic commands ###
